### ISSUE TITLE
Sets up socket middleware returns an error

### ISSUE THREAD

**Issue by dmitxe** [zishang520/socket.io#11]
This code returns an error:

```
        httpServer := types.CreateServer(nil)
 	io := socket.NewServer(httpServer, nil)
 	err = io.On("connection", func(clients ...any) {
 		client := clients[0].(*socket.Socket)
 		client.Use(func(anies []any, f func(error)) {
 			spew.Dump(anies)
 			f(nil)
 		})
 	})
 	if err != nil {
 		fmt.Println("err on conn", err)
 	}
```

Error text :  panic: runtime error: index out of range [1] with length 1
go/pkg/mod/github.com/zishang520/socket.io@v1.0.18/socket/socket.go:517 +0x10d

I think the error is in this line https://github.com/zishang520/socket.io/blob/main/socket/socket.go#L524 
`if i >= length {`
Should take length - 1
`if i >= length - 1 {`

Otherwise, we will get a call to a non-existent i: https://github.com/zishang520/socket.io/blob/main/socket/socket.go#L529

**Comment by zishang520** [comment]
This problem has been fixed in version v1.0.19.
