### ISSUE TITLE
join not working

### ISSUE THREAD

**Issue by m2faridi** [zishang520/socket.io#15]
This code has an error

```
			strRoom := fmt.Sprintf("user_%d", 1234)
			client.Join(Room)
```

**Comment by zishang520** [comment]
@m2faridi Hello, could you please copy and paste your error message?

**Comment by m2faridi** [comment]
hi @zishang520 
fix with this code
`strRoom := fmt.Sprintf("user_%d", 1234)
client.Join(socket.Room(strRoom))`
