### ISSUE TITLE
向服务器Emit为null的事件时fatalpanic

### ISSUE THREAD

**Issue by StormYudi** [zishang520/socket.io#17]
向服务器Emit为null的事件时会导致服务器fatalpanic。

例如在Socket.IO(JavaScript)中，使用：
`socket.emit()`

<img width="736" alt="image" src="https://github.com/zishang520/socket.io/assets/19419186/afe3385f-5bc2-464b-be24-966e7f24260c">

就会导致服务器fatailpanic。

如图：
<img width="951" alt="image" src="https://github.com/zishang520/socket.io/assets/19419186/8dd8ebbd-70bb-4086-a6e1-9b770b270833">

**Comment by StormYudi** [comment]
而且无法recover

**Comment by StormYudi** [comment]
另外我发现在事件的处理中panic的话，并没有栈输出，不知道有没有什么好方法呢

**Comment by zishang520** [comment]
您好，已发布新的版本[v1.1.1](https://github.com/zishang520/socket.io/releases/tag/v1.1.1)用于修复该问题，请更新后再测试下，期待你的反馈信息，感谢。

**Comment by zishang520** [comment]
> 另外我发现在事件的处理中panic的话，并没有栈输出，不知道有没有什么好方法呢

您可以尝试使用以下方法从 socket.io 中捕获异常：

You can try to catch exceptions from socket.io using the following methods: 
```go
io.On("connection", func(clients ...any) {
    client := clients[0].(*socket.Socket)
    client.On("error", func(errors ...any) {
        utils.Log().Error("errors: %v", errors)
    })
})
```

**Comment by zishang520** [comment]
好的，如果没有其它问题，我就关闭这个issue了

Okay, if there are no other questions, I will close this issue.
