### ISSUE TITLE
Which version of socket.io-client does this support?

### ISSUE THREAD

**Issue by zizhong** [zishang520/socket.io#18]
https://github.com/socketio/socket.io-client
Does it support 2.x, 3.x or 4.x?

Thanks,

**Comment by zishang520** [comment]
@zizhong Hello, you can refer to the table content in this [link](https://socket.io/docs/v4/client-installation/#version-compatibility). The latest version v1.1.* corresponds to socket.io version 4.5.*.

**Comment by zizhong** [comment]
Thanks! That sounds good. Probably better to include this information in the document.
