### ISSUE TITLE
Disconnect is not called on server when client lose connection

### ISSUE THREAD

**Issue by Dorbmon** [zishang520/socket.io#21]
Anyway to solve this when client don't call disconnect but just lose connection.

**Comment by zishang520** [comment]
@Dorbmon Hello, the default Ping timeout is 20000 milliseconds

**Comment by Dorbmon** [comment]
@zishang520 But I don't think disconnect event is called after timeout

**Comment by zishang520** [comment]
> @zishang520 But I don't think disconnect event is called after timeout

Hi, can you reproduce your problem?

**Comment by zishang520** [comment]
Hello, has your issue been resolved?
