### ISSUE TITLE
how to join you

### ISSUE THREAD

**Issue by shitingbao** [zishang520/socket.io#3]
Recently used socketio in my go project,I feel unfriend;
So it took me a lot of time to rewrite it using nodejs,
until I see your project ,I very interested in your project,
I hope to do a little bit of my little effort to advance your project, so that other people who have suffered the same way as me will avoid detours

**Comment by zishang520** [comment]
Hello, the project is still in continuous improvement, welcome to submit a reliable pull request.
 I'm still perfecting the unit tests for [engine.io](https://github.com/zishang520/engine.io) , and I'll get back to work when I get back on vacation.  Thanks for your support.
