### ISSUE TITLE
如何实现回调功能

### ISSUE THREAD

**Issue by ctbsea** [zishang520/socket.io#38]
`
Listener func(...any)
`
没有返回参数
怎么实现如下的回调功能
`
server.On("some:event", func(msg string) string {
return msg //Sending ack with data in msg back to client, using "return statement"
})

`

**Comment by ctbsea** [comment]
> 写了一个，可以用这个
> 
> ```go
> type ClientMessage struct {
> 	UserName string `json:"username"`
> 	Payload  string `json:"payload"`
> }
> 
> func Wrapper(event string, client *socket.Socket, handler func(client *socket.Socket, cliMsg *entities.ClientMessage) []byte) func(...any) {
> 	return func(datas ...any) {
> 		logrus.Infof("recive a client event: [%s], datas: %+v", event, datas)
> 		d, ok := datas[0].(string)
> 		if !ok || d == "" {
> 			logrus.Errorf("invalid data type: %+v", datas)
> 			return
> 		}
> 
> 		clientMsg := &entities.ClientMessage{}
> 		if err := json.Unmarshal([]byte(d), clientMsg); err != nil {
> 			logrus.WithError(err).Errorf("invalid data type: %+v", datas)
> 			return
> 		}
> 
> 		r := handler(client, clientMsg)
> 		if len(r) > 0 {
> 			client.Emit(event)
> 		}
> 	}
> }
> 
> func EventHandler() {
> 	server := socket.NewServer(nil, nil)
> 	server.On("connection", func(clients ...any) {
> 		client := clients[0].(*socket.Socket)
> 		client.On("join", Wrapper("join", client, JoinEndpoint))
> 		client.On("disconnect", func(...any) {})
> 	})
> }
> 
> func JoinEndpoint(client *socket.Socket, cliMsg *entities.ClientMessage) []byte {
> 	// do your biz
> }
> ```

https://socket.io/zh-CN/docs/v4/client-api/#socketemiteventname-args-ack

我期望的是这种效果，你提供的代码再客户端无法直接通过response 获取到消息
![image](https://github.com/zishang520/socket.io/assets/4230390/9614f44d-68b9-471d-be7c-39f88dcd21e6)

**Comment by zishang520** [comment]
Use this annotation example:

https://github.com/zishang520/socket.io/blob/57586449cad1cc39c8f9b007d6d5d59cc7bc83f8/socket/socket.go#L273-L286

https://github.com/zishang520/socket.io/blob/57586449cad1cc39c8f9b007d6d5d59cc7bc83f8/socket/socket.go#L325-L353

For more information, please check the documentation: https://pkg.go.dev/github.com/zishang520/socket.io/v2@v2.0.5/socket#Socket.Emit

**Comment by ctbsea** [comment]
> Use this annotation example:
> 
> https://github.com/zishang520/socket.io/blob/57586449cad1cc39c8f9b007d6d5d59cc7bc83f8/socket/socket.go#L273-L286
> 
> https://github.com/zishang520/socket.io/blob/57586449cad1cc39c8f9b007d6d5d59cc7bc83f8/socket/socket.go#L325-L353
> 
> For more information, please check the documentation: https://pkg.go.dev/github.com/zishang520/socket.io/v2@v2.0.5/socket#Socket.Emit


上述提供的都是基于emit 主动发送消息后等待client ack

我是想实现on监听某个事件，当收到客户端消息的时候，处理完消息返回客户端一些消息，


```
官方案例

**Server**
io.on("connection", (socket) => {
  socket.on("hello", (arg, callback) => {
    console.log(arg);  //  "world"
    callback("got it");  //  **我问这个callback 对应的实现方式**
  });
});

**Client**
socket.emit("hello", "world", (response) => {
  console.log(response); // "got it"
});

```

**Comment by ctbsea** [comment]
> > Use this annotation example:
> > https://github.com/zishang520/socket.io/blob/57586449cad1cc39c8f9b007d6d5d59cc7bc83f8/socket/socket.go#L273-L286
> > 
> > https://github.com/zishang520/socket.io/blob/57586449cad1cc39c8f9b007d6d5d59cc7bc83f8/socket/socket.go#L325-L353
> > 
> > For more information, please check the documentation: https://pkg.go.dev/github.com/zishang520/socket.io/v2@v2.0.5/socket#Socket.Emit
> 
> 上述提供的都是基于emit 主动发送消息后等待client ack
> 
> 我是想实现on监听某个事件，当收到客户端消息的时候，处理完消息返回客户端一些消息，
> 
> ```
> 官方案例
> 
> **Server**
> io.on("connection", (socket) => {
>   socket.on("hello", (arg, callback) => {
>     console.log(arg);  //  "world"
>     callback("got it");  //  **我想知道有没有对应的这个callback 对应的实现**
>   });
> });
> 
> **Client**
> socket.emit("hello", "world", (response) => {
>   console.log(response); // "got it"
> });
> ```

**Comment by ctbsea** [comment]
> > > Use this annotation example:
> > > https://github.com/zishang520/socket.io/blob/57586449cad1cc39c8f9b007d6d5d59cc7bc83f8/socket/socket.go#L273-L286
> > > 
> > > https://github.com/zishang520/socket.io/blob/57586449cad1cc39c8f9b007d6d5d59cc7bc83f8/socket/socket.go#L325-L353
> > > 
> > > For more information, please check the documentation: https://pkg.go.dev/github.com/zishang520/socket.io/v2@v2.0.5/socket#Socket.Emit
> > 
> > 
> > 上述提供的都是基于emit 主动发送消息后等待client ack
> > 我是想实现on监听某个事件，当收到客户端消息的时候，处理完消息返回客户端一些消息，
> > ```
> > 官方案例
> > 
> > **Server**
> > io.on("connection", (socket) => {
> >   socket.on("hello", (arg, callback) => {
> >     console.log(arg);  //  "world"
> >     callback("got it");  //  **我想知道有没有对应的这个callback 对应的实现， 如下client能够直接通过response， 如果通过emit 发送response，无法获取返回的内容**
> >   });
> > });
> > 
> > **Client**
> > socket.emit("hello", "world", (response) => {
> >   console.log(response); // "got it"
> > });
> > ```

**Comment by ctbsea** [comment]
client 
```
socket.emit("hello", "world", (response) => {
  console.log(response); // "i'm  join"
});
```

go 

```
io.Of("/", nil).On("connection", func(args ...any) {
      socket := args[0].(*socket.Socket)
      socket.On("join", func(a ...any) {
            msg :=a[0]  // "word"
            // a[1]对应的是client 传递的 (response){}
	    a[1].(func([]interface{}, error))([]interface{}{"i'm  join"}, nil) 
     })
})
```
