### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by iakuf** [zishang520/socket.io#4]
生产环境使用过不? 不知道每一万连接需要占用多少内存, 还有多 redis 是否支持

**Comment by zishang520** [comment]
您好，本项目还在持续改进中，暂无相关压测数据。 你可以先自己测试一下； 其次，暂时不支持redis功能，期待后续改进。 谢谢你的支持。

Hello, this project is still in continuous improvement, and there is no relevant pressure measurement data yet. You can test it yourself first; secondly, the redis function is not supported for the time being, and we look forward to subsequent improvements. Thanks for your support.

**Comment by zishang520** [comment]
Do you have any other questions? If there are no more, the issue will be closed.
