### ISSUE TITLE
ack 回调中的err参数具体是什么？有没有例子？

### ISSUE THREAD

**Issue by vipcxj** [zishang520/socket.io#42]
如题~ 如何主动触发这个error？

**Comment by vipcxj** [comment]
@zishang520  最近遇到个bug，但不确定是不是服务端的，表现为客户端收不到服务端发的消息，并且发生这种情况时，客户端会显示websocket断开过，后面好像是有重连，但丢失的消息就这样没了~ 客户端就是浏览器，也就是官方的js客户端

**Comment by vipcxj** [comment]
@zishang520 这段代码之前有看到过，但是还是不确定这个err具体是什么。只有使用了timeout，err才有意义吗？或者说这个err只有超时才触发吗？如果不使用timeout，是不是意味着永远不会触发err，只会让代码卡在那，永远不返回？

**Comment by zishang520** [comment]
> @zishang520 最近遇到个bug，但不确定是不是服务端的，表现为客户端收不到服务端发的消息，并且发生这种情况时，客户端会显示websocket断开过，后面好像是有重连，但丢失的消息就这样没了~ 客户端就是浏览器，也就是官方的js客户端

You can try enabling session:
```golang
// ...more
c := socket.DefaultServerOptions()
c.SetConnectionStateRecovery(&socket.ConnectionStateRecovery{})

httpServer := types.CreateServer(nil)
io := socket.NewServer(httpServer, c)

// ...more
```

**Comment by zishang520** [comment]
> @zishang520 这段代码之前有看到过，但是还是不确定这个err具体是什么。只有使用了timeout，err才有意义吗？或者说这个err只有超时才触发吗？如果不使用timeout，是不是意味着永远不会触发err，只会让代码卡在那，永远不返回？

Yes, currently there are only timeout error messages. Regarding the logic of not setting a timeout, I will reply to you after confirmation.

**Comment by zishang520** [comment]
> @zishang520 这段代码之前有看到过，但是还是不确定这个err具体是什么。只有使用了timeout，err才有意义吗？或者说这个err只有超时才触发吗？如果不使用timeout，是不是意味着永远不会触发err，只会让代码卡在那，永远不返回？

I've confirmed the Ack logic for the case where no timeout is set:

- If you use `Broadcast().Emit("event", func([]any, error) {})`, it will almost certainly be considered a timeout because the default timeout is `0`.
- If you use `client.Emit("event", func([]any, error) {})`, only one ack function will be registered in the context. The default timeout will not be set, and the function will be destroyed when the client calls or disconnects.

**Comment by vipcxj** [comment]
In my opinion, a timeout of 0 means that it will never time out, after all, a timeout of 0 is meaningless in practice. 

Do you mean that `Broadcast().Emit("event", func([]any, error) {})` is the wrong way to use it in practice? And with `client.Emit("event", func([]any, error) {})` the ack won't be executed at all in the event of a timeout or disconnection. So in a nutshell ack must be executed in conjunction with a timeout or disconnection. So in summary ack must be used in conjunction with timeout, otherwise it's pointless?

**Comment by zishang520** [comment]
> In my opinion, a timeout of 0 means that it will never time out, after all, a timeout of 0 is meaningless in practice.
> 
> Do you mean that `Broadcast().Emit("event", func([]any, error) {})` is the wrong way to use it in practice? And with `client.Emit("event", func([]any, error) {})` the ack won't be executed at all in the event of a timeout or disconnection. So in a nutshell ack must be executed in conjunction with a timeout or disconnection. So in summary ack must be used in conjunction with timeout, otherwise it's pointless?

Yes, it must be used together with timeout in `broadcast`, otherwise it is meaningless.  The `client` is allowed not to set a timeout, This scenario is suitable for the `client` to handle some services with uncertain response time.
