### ISSUE TITLE
EmitwithAck never listens for the callback from the client so it always timed out

### ISSUE THREAD

**Issue by danielAsaboro** [zishang520/socket.io#47]
This is a snippet from my code,
I'm porting a socket service already written in nodejs to go...
and this emitWithAck never returns a response ...it times out.

yet, the client automatically acknowledge the message as soon as it gets it 
(it's instantaneous btw)

```
io.Timeout(180*time.Second).EmitWithAck("this-rider-location", receivedMessage)(
				func(args []any, err error) {
					fmt.Print(err)
					if err == nil {
                                        fmt.Println("we got a response")
                                        }
}
                                        

```

**Comment by danielAsaboro** [comment]
It turns out that it works, but i only get the responses from the acknowledgement (args) after timeout.
is there a way to get it as it arrives (asynchronously)? IIRC, Nodejs does this. And is this a skill issue?

**Comment by zishang520** [comment]
The broadcast EmitWithAck will wait for all clients to respond or time out before returning data.

**Comment by danielAsaboro** [comment]
Hi, thanks for the response.
Please is there an available API to broadcast to the room, and get the callback response when each client does response and not together?

**Comment by zishang520** [comment]
Depending on your needs, you should use Ack for each clinet instead of broadcasting Ack, as in the following example:

```golang
io.On("connection", func(clients ...interface{}) {
		client := clients[0].(*socket.Socket)
		client.EmitWithAck("this-rider-location", "receivedMessage")(
			func(args []any, err error) {
				fmt.Print(err)
				if err == nil {
					fmt.Println("we got a response")
				}
			})
		client.On("disconnect", func(...interface{}) {
			// utils.Log().Success("/ test disconnect")
		})
	})
```

**Comment by danielAsaboro** [comment]
> Return: a `func(func([]any, error))` that will be fulfilled when all clients have acknowledged the event
using client does the same — wait for all client...
my use-case would love to initiate an action as each clients acknowledge not wait for all 

I appreciate the help regardless, thank you

**Comment by zishang520** [comment]
If you have any other questions, please feel free to contact me.
