### ISSUE TITLE
how to fetch /socket.io/socket.io.js ?

### ISSUE THREAD

**Issue by mzafranrashid** [zishang520/socket.io#48]
I use you example, it work for connecting and sending message, but when I try to get the JS client code, using url /socket.io/socket.io.js
I always get error 400 with message below. any example i can follow to get the client JS ?

{
    "code": 0,
    "message": "Transport unknown"
}

**Comment by zishang520** [comment]
```golang
package main

import (
	"os"
	"os/signal"
	"syscall"

	"github.com/zishang520/engine.io/v2/log"
	"github.com/zishang520/engine.io/v2/types"
	"github.com/zishang520/socket.io/v2/socket"
)

func main() {
	log.DEBUG = true
	c := socket.DefaultServerOptions()
	// c.SetConnectionStateRecovery(&socket.ConnectionStateRecovery{})
	// c.SetAllowEIO3(true)
	c.SetServeClient(true)
	// c.SetCors(&types.Cors{
	// 	Origin:      "http://127.0.0.1:8000",
	// 	Credentials: true,
	// })
	httpServer := types.CreateServer(nil)
	io := socket.NewServer(httpServer, c)
	io.On("connection", func(clients ...interface{}) {
		client := clients[0].(*socket.Socket)
		client.On("disconnect", func(...interface{}) {
			// utils.Log().Success("/ test disconnect")
		})
	})
	httpServer.Listen("127.0.0.1:3000", nil)

	exit := make(chan struct{})
	SignalC := make(chan os.Signal)

	signal.Notify(SignalC, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)
	go func() {
		for s := range SignalC {
			switch s {
			case syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT:
				close(exit)
				return
			}
		}
	}()

	<-exit
	io.Close(nil)
	os.Exit(0)
}
```

```shell
$ curl http://127.0.0.1:3000/socket.io/socket.io.js
```

**Comment by CyborgCannotDie** [comment]
> ```go
> package main
> 
> import (
> 	"os"
> 	"os/signal"
> 	"syscall"
> 
> 	"github.com/zishang520/engine.io/v2/log"
> 	"github.com/zishang520/engine.io/v2/types"
> 	"github.com/zishang520/socket.io/v2/socket"
> )
> 
> func main() {
> 	log.DEBUG = true
> 	c := socket.DefaultServerOptions()
> 	// c.SetConnectionStateRecovery(&socket.ConnectionStateRecovery{})
> 	// c.SetAllowEIO3(true)
> 	c.SetServeClient(true)
> 	// c.SetCors(&types.Cors{
> 	// 	Origin:      "http://127.0.0.1:8000",
> 	// 	Credentials: true,
> 	// })
> 	httpServer := types.CreateServer(nil)
> 	io := socket.NewServer(httpServer, c)
> 	io.On("connection", func(clients ...interface{}) {
> 		client := clients[0].(*socket.Socket)
> 		client.On("disconnect", func(...interface{}) {
> 			// utils.Log().Success("/ test disconnect")
> 		})
> 	})
> 	httpServer.Listen("127.0.0.1:3000", nil)
> 
> 	exit := make(chan struct{})
> 	SignalC := make(chan os.Signal)
> 
> 	signal.Notify(SignalC, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)
> 	go func() {
> 		for s := range SignalC {
> 			switch s {
> 			case syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT:
> 				close(exit)
> 				return
> 			}
> 		}
> 	}()
> 
> 	<-exit
> 	io.Close(nil)
> 	os.Exit(0)
> }
> ```
> 
> ```shell
> $ curl http://127.0.0.1:3000/socket.io/socket.io.js
> ```

doesn't work for me, go version go1.22.4 linux/amd64.
server is runnig but curl http://127.0.0.1:3000/socket.io/socket.io.js responds "file not found".
using:
go mod init example-socketio
go mod tidy
go  run .

**Comment by zishang520** [comment]
Please make sure the https://github.com/zishang520/socket.io/tree/main/client-dist directory is located in the same directory as the executable file.

**Comment by zishang520** [comment]
Do you have any other questions? If there are no more, the issue will be closed.
