### ISSUE TITLE
请问socketio的reconnect机制到底啥玩意

### ISSUE THREAD

**Issue by vipcxj** [zishang520/socket.io#49]
socketio的版本太多，除了js的版本，大多数其他语言只支持特别老的版本，导致文档也乱七八糟~
我原本放弃websocket选择socketio，是觉得这东西功能比websocket更强大，有类似房间的机制，最重要的是有自动重连机制，可靠性更高。实际用了才发现全是坑~ 主要是自动重连机制文档语焉不详，我怎么知道重连了？重连有没有回调？socket.on("connection")的回调包含重连吗？如果包含，如何区别第一次连接还是重新连接？最近才发现个大坑，好像重连是客户端机制，服务端是没有的，所以服务端的emit可能都是不可靠的~ 于是我得加代码自己实现在断连期间服务端消息缓存。这就设计到这所谓的重连对于服务的到底是什么情况？
每次重连，服务的都获得一个新的连接？还是重用已有的socket？
目前我的使用场景其实感觉socketio已经不划算了，因为socketio关注的是客户端到客户端，而我这是客户端到服务端集群，然后服务端通过mq消息总线转发消息给集群里的其他服务端，然后再通过某个服务端发送给客户端，这导致基本都是客户端和服务端的交互。这和socketio的设计思想差别有点大。但现在换也来不及了，只能凑合用用~
总之求教下socketio的reconnect机制在服务端的角度到底是个啥玩意

**Comment by zishang520** [comment]
重新连接会更新客户端的sid，导致之前的会话丢失。 在新版本的socketio中，增加了session功能（是基于内存实现的，golang版本也只实现了内存）。

------

Reconnecting will update the client's sid, causing the previous session to be lost. In the new version of socketio, a session function has been added (it is implemented based on memory, and the golang version also only implements memory).

```golang
package main

import (
	"os"
	"os/signal"
	"syscall"

	"github.com/zishang520/engine.io/v2/log"
	"github.com/zishang520/engine.io/v2/types"
	"github.com/zishang520/socket.io/v2/socket"
)

func main() {
	log.DEBUG = true
	c := socket.DefaultServerOptions()
	// 开启Session功能。
	// Enable Session function.
	c.SetConnectionStateRecovery(&socket.ConnectionStateRecovery{})
	// c.SetAllowEIO3(true)
	// c.SetServeClient(true)
	// c.SetCors(&types.Cors{
	// 	Origin:      "http://127.0.0.1:8000",
	// 	Credentials: true,
	// })
	httpServer := types.CreateServer(nil)
	io := socket.NewServer(httpServer, c)
	io.On("connection", func(clients ...interface{}) {
		client := clients[0].(*socket.Socket)
		client.On("disconnect", func(...interface{}) {
			// utils.Log().Success("/ test disconnect")
		})
	})
	httpServer.Listen("127.0.0.1:3000", nil)

	exit := make(chan struct{})
	SignalC := make(chan os.Signal)

	signal.Notify(SignalC, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)
	go func() {
		for s := range SignalC {
			switch s {
			case syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT:
				close(exit)
				return
			}
		}
	}()

	<-exit
	io.Close(nil)
	os.Exit(0)
}
```

**Comment by vipcxj** [comment]
感谢回复。

这里的“disconnect“回调包括重连导致的断开吗？如果包括，如何区分正常断开和重连断开？使用了`c.SetConnectionStateRecovery`之后，重连不会重置连接吗？主要是socket.data()还在吗？我状态一开始都是存这的。虽然后来弄了个全局map又存了一份，但用data更方便，何况就算用全局map，我也得能判断出是重连，然后再从map里取数据，否则这生命周期没法管理~

**Comment by zishang520** [comment]
是的，根据源码，会恢复原来的Data数据。 具体代码请看下面的代码片段：

------

Yes, according to the source code, the original Data data will be restored. Please see the code snippet below for the specific code:

https://github.com/zishang520/socket.io/blob/5cae07d1c5ee3c50f1f535166a63a1c804882ceb/socket/socket.go#L220-L233

**Comment by vipcxj** [comment]
那服务端发送的消息能保证要么成功要么返回error吗？也就是有没有断开期间缓存消息，重连后继续发的机制？

**Comment by zishang520** [comment]
You can check this document to clear your doubts: https://socket.io/docs/v4/connection-state-recovery

**Comment by zishang520** [comment]
Do you have any other questions? If there are no more, the issue will be closed.
