### ISSUE TITLE
Fiber adaptor doesn't work with SocketIO 4+

### ISSUE THREAD

**Issue by herberthobregon** [zishang520/socket.io#69]
I tried to do the example that appears in the Readme but I couldn't get it to work with fiber, it immediately closes the WS connection

![Screenshot 2024-10-13 at 4 26 51 PM](https://github.com/user-attachments/assets/11c79396-02c1-4f4e-9a4e-6a96802f0e56)

**Comment by zishang520** [comment]
Please provide your Fiber version information and socket.io version information.

**Comment by zishang520** [comment]
You need to modify the version of github.com/valyala/fasthttp in `go.mod` to `1.56.0` or above to use it.

**Comment by herberthobregon** [comment]
Thank you. I updated to `go 1.23` and `github.com/valyala/fasthttp 1.56.0`
