### ISSUE TITLE
How do I unset ping/pong?

### ISSUE THREAD

**Issue by jkwang-a** [zishang520/socket.io#75]
c := socket.DefaultServerOptions()
	c.SetPingInterval(30 * time.Second)
	c.SetPingTimeout(60 * time.Second)
	
	Setting to 0 can not be disabled, how to disable a setting

**Comment by zishang520** [comment]
Why do you need to disable it?

**Comment by jkwang-a** [comment]
The guy who built the app asked for it. He always thought it was too much trouble. I can't fight with him

**Comment by jkwang-a** [comment]
@zishang520 
The guy who built the app asked for it. He always thought it was too much trouble. I can't fight with him

**Comment by zishang520** [comment]
Sorry, ping/pong is part of the entire socket.io/engine.io protocol and cannot be disabled.
