### ISSUE TITLE
How to solve CORS issue

### ISSUE THREAD

**Issue by dianyulius** [zishang520/socket.io#8]
Hi @zishang520, how to enable cors options support for this library?

**Comment by zishang520** [comment]
Hello, you can refer to the sample code of this [link](https://github.com/zishang520/socket.io-test/blob/9d4e417e9334f0b6e66632feff7b0499fe1467e9/socket.io.go#L26)  to set the relevant configuration for initialization.

**Comment by dianyulius** [comment]
Okay i'll try it, thanks!

**Comment by zishang520** [comment]
Do you have any other questions? No more questions this question will be closed.
